### PR TITLE
README: Vim (8.2.0929+) includes Elm Syntax Highlighting

### PR DESCRIPTION
**Pull request by andys8**
Hint regarding the included syntax files in Vim

### CODE REVIEW

**Comment by michaeljones** [comment]
Unfortunately I've left Zaptic and so don't have access to merge this. Perhaps @melvisntnormal or @jgresty wouldn't mind merging?

Thanks for the effort to keep the info up to date @andys8.

**Comment by MelvIsntNormal** [comment]
> Unfortunately I've left Zaptic and so don't have access to merge this. Perhaps @MelvIsntNormal or @jgresty wouldn't mind merging?

I can definitely take a look at this :+1:

**Comment by MelvIsntNormal** [comment]
Sorry about this guys, I have asked Ben for write access to this repository but haven't heard anything about it yet. I probably should have told him I wanted to merge this in. @benbabic ?

**Comment by benbabic** [comment]
Done, and you shoud have access. @michaeljones you too, in case you want to change something

**Comment by michaeljones** [comment]
Thanks guys :) I'll try to handle stuff in the future. Shouldn't be too busy :)

**Pull request merged**
