### PR TITLE
 Syntax: Add elm module group

### PR DESCRIPTION
**Pull request by bryanenders**
Why
---

I want to be able to differentiate Elm modules from Elm types

How
---

* Create `elmModule` highlight group
* Link `elmModule` to `Type`, the group conventionally used for modules

Side effects
------------

This PR brings the fork up-to-date with upstream, which may or may not be desirable. The `
Syntax: Add elm module group` commit may be cherry-picked.

### CODE REVIEW

**Comment by michaeljones** [comment]
Thanks for the PR! It'll take me a bit of time to work though and I suspect I might prefer just to focus on the last commit for the moment if that's what you're most interested in. It'll be good to review the other differences though.

**Comment by bryanenders** [comment]
@michaeljones Feel free to cherry pick the last commit.

**Comment by michaeljones** [comment]
Yeah, sorry for the silence. Not cool. I'll try to get that done today.

**Comment by michaeljones** [comment]
I've cherry-picked the syntax related commits and merged them to master. I really appreciate the modules vs types stuff, so thank you for that! 

If any of the other stuff is important, please let me know otherwise I'll try to give it more attention at some point :)

**Comment by michaeljones** [comment]
I'm seeing issues with it not highlighting `in` properly and sometimes not highlighting the `|>` operator correctly. I think this might need some work. I might back out some of the other changes. Any help & advice would be welcome.

**Comment by bryanenders** [comment]
Do you get those issues if you cherry pick _only_ the last commit (i.e., reverse “wip: first stab at folding” and “Multiline type declaration highlighting”)?

I made this PR using the commit I branched from ElmCast/elm-vim/master for convenience. In hindsight, I should have made a separate branch off this fork for this PR. Sorry for the headaches!

**Comment by michaeljones** [comment]
I've reverted everything and taken yours. I originally took them all as there are conflicts if you don't and I don't know much about syntax files so I didn't want to risk anything, but in the end there were too many annoying things and errors.

Your commit seems to work fine, so hopefully we can stick with the current state.

**Comment by bryanenders** [comment]
Thanks for getting that sussed out, @michaeljones. I love this fork and only wish I’d found it sooner!

**Comment by michaeljones** [comment]
Thanks for saying that. I'm glad it is providing value :)

It is hard to make Github forks easily discoverable. I'm confused why the main ElmCasts repository hasn't been handled over to other maintainers or changed to point the way to alternatives somehow. Quite strange to me given how young Elm is as a language & ecosystem.

**Comment by andys8** [comment]
@endersstocker Hey, can you help me understand how the changes are supposed to look for the user? I cherry picked and applied them on the right side:

image

Differences:
-  `exposing` and `as` loose their highlights
- `import` and `module` look the same as functions

It maybe due to the color scheme or a mistake on my side. Would be great if you could elaborate if this is expected. Thanks.

**Pull request closed without merging**
